//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLink.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartLink.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sharepoint access token failed..
        /// </summary>
        public static string AccessTokenFailed {
            get {
                return ResourceManager.GetString("AccessTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add bulk.
        /// </summary>
        public static string AddBulk {
            get {
                return ResourceManager.GetString("AddBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Destination Point.
        /// </summary>
        public static string AddDestPoint {
            get {
                return ResourceManager.GetString("AddDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add edit .
        /// </summary>
        public static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source point failed..
        /// </summary>
        public static string AddNewSourcePointFailed {
            get {
                return ResourceManager.GetString("AddNewSourcePointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new source point succeeded.
        /// </summary>
        public static string AddNewSourcePointOK {
            get {
                return ResourceManager.GetString("AddNewSourcePointOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new source table succeeded..
        /// </summary>
        public static string AddNewSourceTableOK {
            get {
                return ResourceManager.GetString("AddNewSourceTableOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add single.
        /// </summary>
        public static string AddSingle {
            get {
                return ResourceManager.GetString("AddSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source Chart.
        /// </summary>
        public static string AddSourceChart {
            get {
                return ResourceManager.GetString("AddSourceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source chart failed..
        /// </summary>
        public static string AddSourceChartFailed {
            get {
                return ResourceManager.GetString("AddSourceChartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new source chart succeeded..
        /// </summary>
        public static string AddSourceChartOK {
            get {
                return ResourceManager.GetString("AddSourceChartOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source Point.
        /// </summary>
        public static string AddSourcePoint {
            get {
                return ResourceManager.GetString("AddSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source Table.
        /// </summary>
        public static string AddSourceTable {
            get {
                return ResourceManager.GetString("AddSourceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source table failed..
        /// </summary>
        public static string AddSourceTableFailed {
            get {
                return ResourceManager.GetString("AddSourceTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Table.
        /// </summary>
        public static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All source points have been deleted..
        /// </summary>
        public static string AllSourcePointsDeleted {
            get {
                return ResourceManager.GetString("AllSourcePointsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        public static string Billion {
            get {
                return ResourceManager.GetString("Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing this destination point cannot be undone..
        /// </summary>
        public static string CannotRemoveDestPoint {
            get {
                return ResourceManager.GetString("CannotRemoveDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing these destination points cannot be undone..
        /// </summary>
        public static string CannotRemoveSelectedDestPoint {
            get {
                return ResourceManager.GetString("CannotRemoveSelectedDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the clone file status failed..
        /// </summary>
        public static string CheckCloneStatusFailed {
            get {
                return ResourceManager.GetString("CheckCloneStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to reload document ID.
        /// </summary>
        public static string ClickReload {
            get {
                return ResourceManager.GetString("ClickReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Browse to select a destination folder.
        /// </summary>
        public static string ClickSelectDestFolder {
            get {
                return ResourceManager.GetString("ClickSelectDestFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Browse to select a source folder.
        /// </summary>
        public static string ClickSelectSourceFolder {
            get {
                return ResourceManager.GetString("ClickSelectSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the clone file status failed..
        /// </summary>
        public static string CloneFileStatusFailed {
            get {
                return ResourceManager.GetString("CloneFileStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Folder.
        /// </summary>
        public static string CloneFolder {
            get {
                return ResourceManager.GetString("CloneFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone folder failed..
        /// </summary>
        public static string CloneFolderFailed {
            get {
                return ResourceManager.GetString("CloneFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning.
        /// </summary>
        public static string Cloning {
            get {
                return ResourceManager.GetString("Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel cloning?.
        /// </summary>
        public static string CloningMessage {
            get {
                return ResourceManager.GetString("CloningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder failed: A file name can&apos;t contain any of the following characters:&lt;br/&gt;\/:*?\&quot;&lt;&gt;|.
        /// </summary>
        public static string CreateFolderFailed {
            get {
                return ResourceManager.GetString("CreateFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create range in Excel failed..
        /// </summary>
        public static string CreateRangeExcelFailed {
            get {
                return ResourceManager.GetString("CreateRangeExcelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create range in Word failed..
        /// </summary>
        public static string CreateRangeFailed {
            get {
                return ResourceManager.GetString("CreateRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create source point name range in Excel failed..
        /// </summary>
        public static string CreateSourcePointNameExcelFailed {
            get {
                return ResourceManager.GetString("CreateSourcePointNameExcelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create source point name range in Excel failed..
        /// </summary>
        public static string CreateSourcePointRangeExcelFailed {
            get {
                return ResourceManager.GetString("CreateSourcePointRangeExcelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table range in Excel failed..
        /// </summary>
        public static string CreateTableRangeExcelFailed {
            get {
                return ResourceManager.GetString("CreateTableRangeExcelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal place.
        /// </summary>
        public static string DecimalPlace {
            get {
                return ResourceManager.GetString("DecimalPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease decimal places.
        /// </summary>
        public static string DecreaseDecimalPlaces {
            get {
                return ResourceManager.GetString("DecreaseDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the destination point?.
        /// </summary>
        public static string DeleteDestPoint {
            get {
                return ResourceManager.GetString("DeleteDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete destination point failed..
        /// </summary>
        public static string DeleteDestPointFailed {
            get {
                return ResourceManager.GetString("DeleteDestPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete destination point succeeded..
        /// </summary>
        public static string DeleteDestPointOK {
            get {
                return ResourceManager.GetString("DeleteDestPointOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete destination point in Word failed..
        /// </summary>
        public static string DeleteDestPointWord {
            get {
                return ResourceManager.GetString("DeleteDestPointWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the previous range failed..
        /// </summary>
        public static string DeletePreviousRangeFailed {
            get {
                return ResourceManager.GetString("DeletePreviousRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the previous source point name range failed..
        /// </summary>
        public static string DeletePreviousSourcePointNameRangeFailed {
            get {
                return ResourceManager.GetString("DeletePreviousSourcePointNameRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the previous table range failed..
        /// </summary>
        public static string DeletePreviousTableRangeFailed {
            get {
                return ResourceManager.GetString("DeletePreviousTableRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected destination point?.
        /// </summary>
        public static string DeleteSelectedDestPoint {
            get {
                return ResourceManager.GetString("DeleteSelectedDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected source.
        /// </summary>
        public static string DeleteSelectedSourcePoint {
            get {
                return ResourceManager.GetString("DeleteSelectedSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete source.
        /// </summary>
        public static string DeleteSource {
            get {
                return ResourceManager.GetString("DeleteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the source.
        /// </summary>
        public static string DeleteSourcePoint {
            get {
                return ResourceManager.GetString("DeleteSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        public static string DestinationFolder {
            get {
                return ResourceManager.GetString("DestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content control that was bound to the source point for this destination point has been removed, please deleted destination point..
        /// </summary>
        public static string DestinationPointRemoved {
            get {
                return ResourceManager.GetString("DestinationPointRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination point has been deleted..
        /// </summary>
        public static string DestPointDeleted {
            get {
                return ResourceManager.GetString("DestPointDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed decimals.
        /// </summary>
        public static string DisplayedDecimals {
            get {
                return ResourceManager.GetString("DisplayedDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get file Document ID failed..
        /// </summary>
        public static string DocumentIdFailed {
            get {
                return ResourceManager.GetString("DocumentIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Value.
        /// </summary>
        public static string DocumentValue {
            get {
                return ResourceManager.GetString("DocumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Custom Format.
        /// </summary>
        public static string EditCustomFormat {
            get {
                return ResourceManager.GetString("EditCustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Source Chart.
        /// </summary>
        public static string EditSourceChart {
            get {
                return ResourceManager.GetString("EditSourceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source chart failed..
        /// </summary>
        public static string EditSourceChartFailed {
            get {
                return ResourceManager.GetString("EditSourceChartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Source Point.
        /// </summary>
        public static string EditSourcePoint {
            get {
                return ResourceManager.GetString("EditSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source point failed..
        /// </summary>
        public static string EditSourcePointFailed {
            get {
                return ResourceManager.GetString("EditSourcePointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Source Table.
        /// </summary>
        public static string EditSourceTable {
            get {
                return ResourceManager.GetString("EditSourceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source table failed..
        /// </summary>
        public static string EditSourceTableFailed {
            get {
                return ResourceManager.GetString("EditSourceTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &quot;edit workbook&quot; button under the excel ribbon..
        /// </summary>
        public static string EditWorkbookButton {
            get {
                return ResourceManager.GetString("EditWorkbookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter folder name..
        /// </summary>
        public static string EnterFolderName {
            get {
                return ResourceManager.GetString("EnterFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following required fields:.
        /// </summary>
        public static string EnterRequiredFields {
            get {
                return ResourceManager.GetString("EnterRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred:.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files associated with this Source Point.
        /// </summary>
        public static string FilesAssociatedWithThisSourcePoint {
            get {
                return ResourceManager.GetString("FilesAssociatedWithThisSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted value.
        /// </summary>
        public static string FormattedValue {
            get {
                return ResourceManager.GetString("FormattedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get associated files failed..
        /// </summary>
        public static string GetAssociatedFilesFailed {
            get {
                return ResourceManager.GetString("GetAssociatedFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get files in destination folder failed..
        /// </summary>
        public static string GetDestFilesFailed {
            get {
                return ResourceManager.GetString("GetDestFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get files failed..
        /// </summary>
        public static string GetFilesFailed {
            get {
                return ResourceManager.GetString("GetFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get files in source folder failed..
        /// </summary>
        public static string GetFilesSourceFolderFailed {
            get {
                return ResourceManager.GetString("GetFilesSourceFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get libraries failed..
        /// </summary>
        public static string GetLibrariesFailed {
            get {
                return ResourceManager.GetString("GetLibrariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get library name failed..
        /// </summary>
        public static string GetLibraryNameFailed {
            get {
                return ResourceManager.GetString("GetLibraryNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get selected cell failed..
        /// </summary>
        public static string GetSelectedCellFailed {
            get {
                return ResourceManager.GetString("GetSelectedCellFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sites failed..
        /// </summary>
        public static string GetSitesFailed {
            get {
                return ResourceManager.GetString("GetSitesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get files in source folder failed..
        /// </summary>
        public static string GetSourceFilesFailed {
            get {
                return ResourceManager.GetString("GetSourceFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get source table styles failed..
        /// </summary>
        public static string GetSourceTableStylesFailed {
            get {
                return ResourceManager.GetString("GetSourceTableStylesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get graph access token failed..
        /// </summary>
        public static string GraphTokenFailed {
            get {
                return ResourceManager.GetString("GraphTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been deleted..
        /// </summary>
        public static string HasBeenDeleted {
            get {
                return ResourceManager.GetString("HasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Off.
        /// </summary>
        public static string HighlightOff {
            get {
                return ResourceManager.GetString("HighlightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight On.
        /// </summary>
        public static string HighlightOn {
            get {
                return ResourceManager.GetString("HighlightOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hundred.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase decimal places.
        /// </summary>
        public static string IncreaseDecimalPlaces {
            get {
                return ResourceManager.GetString("IncreaseDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid. This could be caused by not saving the excel file after creating the source point. Please delete the source.
        /// </summary>
        public static string InvalidNotSavingExcel {
            get {
                return ResourceManager.GetString("InvalidNotSavingExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid..
        /// </summary>
        public static string IsInvalid {
            get {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load charts in worksheet failed..
        /// </summary>
        public static string LoadChartsWorksheetFailed {
            get {
                return ResourceManager.GetString("LoadChartsWorksheetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load custom format failed..
        /// </summary>
        public static string LoadCustomFormatFailed {
            get {
                return ResourceManager.GetString("LoadCustomFormatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load document ID failed.
        /// </summary>
        public static string LoadDocumentIdFailed {
            get {
                return ResourceManager.GetString("LoadDocumentIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load worksheets failed..
        /// </summary>
        public static string LoadWorksheetFailed {
            get {
                return ResourceManager.GetString("LoadWorksheetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cell value or location is not the same with the one in Add-in. Please click &apos;No&apos; to cancel it and click &apos;refresh&apos; to manually sync the value or location from excel to Add-in. Are you sure to publish the selected source point still?.
        /// </summary>
        public static string LocationNotTheSame {
            get {
                return ResourceManager.GetString("LocationNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current login gets expired and needs re-authenticate. You will be redirected to the login page by click OK..
        /// </summary>
        public static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Destination Points.
        /// </summary>
        public static string ManageDestinationPoints {
            get {
                return ResourceManager.GetString("ManageDestinationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Source Points.
        /// </summary>
        public static string ManageSourcePoints {
            get {
                return ResourceManager.GetString("ManageSourcePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new destination point succeeded..
        /// </summary>
        public static string NewDestPoint {
            get {
                return ResourceManager.GetString("NewDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add destination point failed..
        /// </summary>
        public static string NewDestPointFailed {
            get {
                return ResourceManager.GetString("NewDestPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom formatting applied.
        /// </summary>
        public static string NoCustomFormatApplied {
            get {
                return ResourceManager.GetString("NoCustomFormatApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found in source folder..
        /// </summary>
        public static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found in source folder..
        /// </summary>
        public static string NoFilesInSourceFolder {
            get {
                return ResourceManager.GetString("NoFilesInSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent files.
        /// </summary>
        public static string NoRecentFiles {
            get {
                return ResourceManager.GetString("NoRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no source point..
        /// </summary>
        public static string NoSourcePoint {
            get {
                return ResourceManager.GetString("NoSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is not in sync with the catalog, please click refresh to synchronize..
        /// </summary>
        public static string NotInSync {
            get {
                return ResourceManager.GetString("NotInSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 cell can be selected for.
        /// </summary>
        public static string Only1CellCanBeSelected {
            get {
                return ResourceManager.GetString("Only1CellCanBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only support less then 26 keywords..
        /// </summary>
        public static string Only26Chars {
            get {
                return ResourceManager.GetString("Only26Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 adjacent columns can be selected..
        /// </summary>
        public static string Only2AdjacentColumns {
            get {
                return ResourceManager.GetString("Only2AdjacentColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers are a valid input..
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point in Word has been deleted..
        /// </summary>
        public static string PointDeletedInWord {
            get {
                return ResourceManager.GetString("PointDeletedInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please disable your pop-up blocker and reset the add-in by closing it and adding it again..
        /// </summary>
        public static string PopUpBlockerMessage {
            get {
                return ResourceManager.GetString("PopUpBlockerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position is invalid..
        /// </summary>
        public static string PositionIsInvalid {
            get {
                return ResourceManager.GetString("PositionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish All.
        /// </summary>
        public static string PublishAll {
            get {
                return ResourceManager.GetString("PublishAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Cancelled: No changes detected, click the refresh button and try again..
        /// </summary>
        public static string PublishCancelled {
            get {
                return ResourceManager.GetString("PublishCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Status.
        /// </summary>
        public static string PublishedStatus {
            get {
                return ResourceManager.GetString("PublishedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish source point failed..
        /// </summary>
        public static string PublishSourcePointFailed {
            get {
                return ResourceManager.GetString("PublishSourcePointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range in the Excel has been deleted..
        /// </summary>
        public static string RangeInExcelDeleted {
            get {
                return ResourceManager.GetString("RangeInExcelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load recent files failed..
        /// </summary>
        public static string RecentFilesFailed {
            get {
                return ResourceManager.GetString("RecentFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and recreate it..
        /// </summary>
        public static string RecreateIt {
            get {
                return ResourceManager.GetString("RecreateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh All.
        /// </summary>
        public static string RefreshAll {
            get {
                return ResourceManager.GetString("RefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all destination points succeeded..
        /// </summary>
        public static string RefreshDestinationPoints {
            get {
                return ResourceManager.GetString("RefreshDestinationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all source points succeeded..
        /// </summary>
        public static string RefreshSourcePoints {
            get {
                return ResourceManager.GetString("RefreshSourcePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset sort.
        /// </summary>
        public static string ResetSort {
            get {
                return ResourceManager.GetString("ResetSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a source point.
        /// </summary>
        public static string SearchSourcePoint {
            get {
                return ResourceManager.GetString("SearchSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Source Point Name.
        /// </summary>
        public static string SearchSourcePointName {
            get {
                return ResourceManager.GetString("SearchSourcePointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chart.
        /// </summary>
        public static string SelectChart {
            get {
                return ResourceManager.GetString("SelectChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select destination point..
        /// </summary>
        public static string SelectDestPoint {
            get {
                return ResourceManager.GetString("SelectDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists, please select a different name..
        /// </summary>
        public static string SelectDifferentName {
            get {
                return ResourceManager.GetString("SelectDifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected range cannot be blank..
        /// </summary>
        public static string SelectedRangeCannotBeBlank {
            get {
                return ResourceManager.GetString("SelectedRangeCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source points you selected have been deleted..
        /// </summary>
        public static string SelectedSourcePointsDeleted {
            get {
                return ResourceManager.GetString("SelectedSourcePointsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to clone.
        /// </summary>
        public static string SelectFolderToClone {
            get {
                return ResourceManager.GetString("SelectFolderToClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from recent files.
        /// </summary>
        public static string SelectFromRecentFiles {
            get {
                return ResourceManager.GetString("SelectFromRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select source point, table or chart..
        /// </summary>
        public static string SelectPointTableChart {
            get {
                return ResourceManager.GetString("SelectPointTableChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Range.
        /// </summary>
        public static string SelectRange {
            get {
                return ResourceManager.GetString("SelectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source point name.
        /// </summary>
        public static string SelectSourcePointName {
            get {
                return ResourceManager.GetString("SelectSourcePointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get site collection ID failed..
        /// </summary>
        public static string SiteCollectionIdFailed {
            get {
                return ResourceManager.GetString("SiteCollectionIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get site url failed..
        /// </summary>
        public static string SiteUrlFailed {
            get {
                return ResourceManager.GetString("SiteUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source chart in the Excel has been deleted..
        /// </summary>
        public static string SourceChartExcelDeleted {
            get {
                return ResourceManager.GetString("SourceChartExcelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Chart Title.
        /// </summary>
        public static string SourceChartTitle {
            get {
                return ResourceManager.GetString("SourceChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source chart update complete..
        /// </summary>
        public static string SourceChartUpdateComplete {
            get {
                return ResourceManager.GetString("SourceChartUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file used for this destination point has been deleted from the catalog, please delete the destination point and use a valid source point..
        /// </summary>
        public static string SourceFileDeletedMessage {
            get {
                return ResourceManager.GetString("SourceFileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Point.
        /// </summary>
        public static string SourcePoint {
            get {
                return ResourceManager.GetString("SourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source point name cannot exceed 255 characters..
        /// </summary>
        public static string SourcePoint255Chars {
            get {
                return ResourceManager.GetString("SourcePoint255Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Point(s) have been added to the catalog..
        /// </summary>
        public static string SourcePointAddedCatalog {
            get {
                return ResourceManager.GetString("SourcePointAddedCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source point name cannot be blank..
        /// </summary>
        public static string SourcePointCannotBeBlank {
            get {
                return ResourceManager.GetString("SourcePointCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Source Points already exist, please input a unique name:.
        /// </summary>
        public static string SourcePointExists {
            get {
                return ResourceManager.GetString("SourcePointExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load source points failed..
        /// </summary>
        public static string SourcePointFailed {
            get {
                return ResourceManager.GetString("SourcePointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source point failed..
        /// </summary>
        public static string SourcePointFailedExcel {
            get {
                return ResourceManager.GetString("SourcePointFailedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Point Name.
        /// </summary>
        public static string SourcePointName {
            get {
                return ResourceManager.GetString("SourcePointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source point name range in the Excel has been deleted..
        /// </summary>
        public static string SourcePointRangeExcelDeleted {
            get {
                return ResourceManager.GetString("SourcePointRangeExcelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source point used for this destination point has been deleted from the catalog, please delete the destination point and use a valid source point..
        /// </summary>
        public static string SourcePointRemovedCatalog {
            get {
                return ResourceManager.GetString("SourcePointRemovedCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all Source Points were published, please check Source Point list for errors..
        /// </summary>
        public static string SourcePointsPublishedFailed {
            get {
                return ResourceManager.GetString("SourcePointsPublishedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish source point succeeded..
        /// </summary>
        public static string SourcePointsPublishedOK {
            get {
                return ResourceManager.GetString("SourcePointsPublishedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source points succeeded, add.
        /// </summary>
        public static string SourcePointsSucceeded {
            get {
                return ResourceManager.GetString("SourcePointsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source point update complete..
        /// </summary>
        public static string SourcePointUpdateComplete {
            get {
                return ResourceManager.GetString("SourcePointUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source point value.
        /// </summary>
        public static string SourcePointValue {
            get {
                return ResourceManager.GetString("SourcePointValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source table title cannot exceed 255 characters..
        /// </summary>
        public static string SourceTable255Chars {
            get {
                return ResourceManager.GetString("SourceTable255Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source table cannot be blank..
        /// </summary>
        public static string SourceTableCannotBeBlank {
            get {
                return ResourceManager.GetString("SourceTableCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Table Range.
        /// </summary>
        public static string SourceTableRange {
            get {
                return ResourceManager.GetString("SourceTableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Table Title.
        /// </summary>
        public static string SourceTableTitle {
            get {
                return ResourceManager.GetString("SourceTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source table title cannot be blank..
        /// </summary>
        public static string SourceTableTitleCannotBeBlank {
            get {
                return ResourceManager.GetString("SourceTableTitleCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source table update complete..
        /// </summary>
        public static string SourceTableUpdateComplete {
            get {
                return ResourceManager.GetString("SourceTableUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want the value to stay in the document?.
        /// </summary>
        public static string StayInDoc {
            get {
                return ResourceManager.GetString("StayInDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table must contain at least 2 rows and 2 columns, please try again..
        /// </summary>
        public static string TableMustHave2Rows {
            get {
                return ResourceManager.GetString("TableMustHave2Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table range in the Excel has been deleted..
        /// </summary>
        public static string TableRangeExcelDeleted {
            get {
                return ResourceManager.GetString("TableRangeExcelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected.
        /// </summary>
        public static string TheSelected {
            get {
                return ResourceManager.GetString("TheSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source.
        /// </summary>
        public static string TheSource {
            get {
                return ResourceManager.GetString("TheSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update destination point custom format succeeded..
        /// </summary>
        public static string UpdateDestPoint {
            get {
                return ResourceManager.GetString("UpdateDestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update destination point custom format failed..
        /// </summary>
        public static string UpdateDestPointFailed {
            get {
                return ResourceManager.GetString("UpdateDestPointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update range in Word failed..
        /// </summary>
        public static string UpdateRangeFailed {
            get {
                return ResourceManager.GetString("UpdateRangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheet in the Excel has been deleted..
        /// </summary>
        public static string WorksheetExcelDeleted {
            get {
                return ResourceManager.GetString("WorksheetExcelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
